package com.example.selfcareapp.data.entity;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Room entity representing an application user.
 * Stores basic user profile data and account creation timestamp.
 */
@Entity(tableName = "users")
public class UserEntity {

    /**
     * Unique identifier of the user.
     * Automatically generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    public int id;

    /**
     * Display name of the user.
     */
    public String name;

    /**
     * Account creation timestamp in milliseconds (Unix epoch).
     */
    public long createdAt;
}