package com.example.selfcareapp.ui.chat;

/**
 * Immutable model representing a single chat message.
 *
 * TYPE_USER -> message sent by the user
 * TYPE_BOT  -> response generated by the assistant
 */
public class ChatMessage {

    public static final int TYPE_USER = 0;
    public static final int TYPE_BOT = 1;

    private final String text;
    private final int type;

    public ChatMessage(String text, int type) {
        this.text = text;
        this.type = type;
    }

    public String getText() {
        return text;
    }

    public int getType() {
        return type;
    }
}
